version: '3.4'

services:
  mycatalogdb:
    image: mongo

  mybasketdb:
    image: redis:alpine

  mycatalog.api:
    image: ${DOCKER_REGISTRY-}mycatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  mybasket.api:
    image: ${DOCKER_REGISTRY-}mybasketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  mongo_data:
