version: '3.4'

services:
  mycatalogdb:
    container_name: mycatalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mybasketdb:
    container_name: mybasketdb
    restart: always
    ports:
     - "6379:6379"

  mycatalog.api:
    container_name: mycatalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mycatalogdb:27017"
    depends_on:
      - mycatalogdb
    ports:
      - "8050:80"

  mybasket.api:
    container_name: mybasket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=mybasketdb:6379"
    depends_on:
      - mybasketdb
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
