version: '3.4'

services:
  mycatalogdb:
    image: mongo

  mybasketdb:
    image: redis:alpine

  myportainer:
    image: portainer/portainer-ce

  mydiscountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  mycatalog.api:
    image: ${DOCKER_REGISTRY-}mycatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  mybasket.api:
    image: ${DOCKER_REGISTRY-}mybasketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  mydiscount.api:
    image: ${DOCKER_REGISTRY-}mydiscountapi
    build:
      context: .
      dockerfile: Services/Discount.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
