version: '3.4'

services:
  mycatalogdb:
    container_name: mycatalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mybasketdb:
    container_name: mybasketdb
    restart: always
    ports:
     - "6379:6379"

  mydiscountdb:
    container_name: mydiscountdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=MyDiscountDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  myportainer:
    container_name: myportainer
    restart: always
    ports:
      - "8060:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  mycatalog.api:
    container_name: mycatalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mycatalogdb:27017"
    depends_on:
      - mycatalogdb
    ports:
      - "8000:80"

  mybasket.api:
    container_name: mybasket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=mybasketdb:6379"
      - "GrpcSettings:DiscountUrl=https://discount.grpc"
    depends_on:
      - mybasketdb
    ports:
      - "8001:80"

  mydiscount.api:
    container_name: mydiscount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=mydiscountdb;Port=5432;Database=MyDiscountDB;User Id=admin;Password=admin1234"
    depends_on:
      - mydiscountdb
    ports:
      - "8002:80"


  mydiscount.grpc:
    container_name: mydiscount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=mydiscountdb;Port=5432;Database=MyDiscountDB;User Id=admin;Password=admin1234"
    depends_on:
      - mydiscountdb
    ports:
      - "8003:80"
