version: '3.4'

services:
  mycatalogdb:
    container_name: mycatalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mycatalog.api:
    container_name: mycatalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mycatalogdb:27017"
    depends_on:
      - mycatalogdb
    ports:
      - "8050:80"