version: '3.4'

services:
  mycatalogdb:
    image: mongo

  mybasketdb:
    image: redis:alpine

  myportainer:
    image: portainer/portainer-ce

  mydiscountdb:
    image: postgres

  myorderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  pgadmin:
    image: dpage/pgadmin4

  mycatalog.api:
    image: ${DOCKER_REGISTRY-}mycatalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  mybasket.api:
    image: ${DOCKER_REGISTRY-}mybasketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  mydiscount.api:
    image: ${DOCKER_REGISTRY-}mydiscountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  mydiscount.grpc:
    image: ${DOCKER_REGISTRY-}mydiscountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile



  myordering.api:
    image: ${DOCKER_REGISTRY-}myorderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile

  shopping.aggregator:
    image: ${DOCKER_REGISTRY-}shoppingaggregator
    build:
      context: .
      dockerfile: ApiGateways/Shopping.Aggregator/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:





